<?xml version="1.0"?>
<package format="3">
  <name>pointcloud_colorize</name>
  <version>0.0.1</version>
  <description>Colorize a LiDAR point cloud using a camera image (ZED) and TF.</description>
  <maintainer email="teal@example.com">teal</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>sensor_msgs_py</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
